name: Manual Publish to NPM

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  packages: write

jobs:
  manual-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        
      - name: Build package
        run: npm run build:all
        
      - name: Bump version (if manual trigger)
        if: github.event_name == 'workflow_dispatch'
        run: |
          npm version ${{ github.event.inputs.version_type }} --no-git-tag-version
          echo "NEW_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          
      - name: Check if version already exists on npm
        if: github.event_name == 'workflow_dispatch'
        id: check_npm_version
        run: |
          # Check if version already exists on npm
          if npm view rwanda-geo@${{ env.NEW_VERSION }} version >/dev/null 2>&1; then
            echo "Version ${{ env.NEW_VERSION }} already exists on npm"
            echo "version_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Version ${{ env.NEW_VERSION }} is new"
            echo "version_exists=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Build with new version
        if: github.event_name == 'workflow_dispatch'
        run: npm run build:all
        
      - name: Publish to NPM
        if: github.event_name == 'workflow_dispatch' && steps.check_npm_version.outputs.version_exists == 'false'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Skip NPM publish (version already exists)
        if: github.event_name == 'workflow_dispatch' && steps.check_npm_version.outputs.version_exists == 'true'
        run: |
          echo "Version ${{ env.NEW_VERSION }} already exists on npm. Skipping publish."
          echo "This usually happens when the workflow runs multiple times."
          
      - name: Create Git tag and push (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json package-lock.json
          git commit -m "Bump version to ${{ env.NEW_VERSION }} [skip ci]"
          git tag v${{ env.NEW_VERSION }}
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin main
          git push origin v${{ env.NEW_VERSION }}
          
      - name: Create GitHub Release (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.NEW_VERSION }}
          release_name: Release v${{ env.NEW_VERSION }}
          body: |
            ## What's Changed
            
            This release includes updates and improvements to the Rwanda Geo package.
            
            ### Version: ${{ env.NEW_VERSION }}
            
            **Changes since last release:**
            - Manual release creation
            - Version alignment improvements
            - Enhanced data management
            
            ### Installation
            ```bash
            npm install rwanda-geo@${{ env.NEW_VERSION }}
            ```
            
            ### Bundle Size
            ~135KB (optimized)
            
            ---
            *This release was automatically generated by GitHub Actions.*
          draft: false
          prerelease: false 